### PR TITLE
More updates for 1.9.2 compatibility, and updates for new version of Tinder

### PR DESCRIPTION
**Pull request by jmoses**

### CODE REVIEW

**Comment by joshwand** [comment]
ok, that's funny. I just did a whole bunch of these changes yesterday myself! I just haven't pushed them yet. 

There's also a problem with the current version of tinder that breaks listen support... see my patch at joshwand/tinder@e561a6a66e

will push my updates in a few hours... then i'll check out your plugin patches.

**Comment by jmoses** [comment]
For my current code + tinder 1.4.3, listen has been working for me.  Is that the newest ver?

**Comment by joshwand** [comment]
I'll give it a shot. I have a feeling that your require 'active_support/all' fixed it, but it's really a tinder bug that needs to be fixed; see collectiveidea/tinder#13

**Comment by jmoses** [comment]
I'm all about work arounds. ;)

**Comment by noahd1** [comment]
I experienced campfire-bot just silently failing unless I included "json" as a dependency in the Gemfile. Perhaps others are seeing more hard failures, but it was particularly tricky for me to track down. Perhaps it's worth it to include this dependency in campfire-bot, or fork tinder to include the dependency?

**Comment by joshwand** [comment]
see collectiveidea/tinder#17 . Doesn't appear to be applied to github yet but he says it's applied...

**Comment by noahd1** [comment]
Thanks. I nudged it.

**Comment by joshwand** [comment]
fixed upstream in tinder.

**Pull request closed without merging**
