### PR TITLE
Gemified campfire-bot

### PR DESCRIPTION
**Pull request by hoverlover**
There are a lot of commits in this pull request, I know.  The gist of the commits, however, is that I've converted the bot to a gem.  This is more convenient, in my opinion, because it allows someone to run the bot more easily on a platform like Heroku.  Having it in gem form, a user can create a simple Rack application and include the campfire-bot gem, and be on their way.

Also, I've created a [few](https://github.com/hoverlover/campfire-bot-standup) [plugins](https://github.com/hoverlover/campfire-bot-absentee-camper) which are also gems.  It would be nice to see all campfire-bot plugins become gems.  This way, the user would only install the campfire-bot, and any plugin gems they wanted to use.  This is similar to how guard works.  I think this approach keeps the campfire-bot codebase cleaner, slimmer and focused on the core functionality.

I am going to go ahead and release the gem for anyone that is interested in using it.  When you are ready to merge in the pull request I will gladly yank all versions and allow you to [take over the gem namespace](http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem).

I welcome any feedback you have.

### CODE REVIEW

**Comment by joshwand** [comment]
Hi, I'm going to borrow liberally from these commits to gemify campfire-bot and gemify the plugins as well... but the pull request is a bit messy so I won't be doing a straight merge. 

This is something I've been planning to do for a while, but haven't had the time... thanks for the head start!

**Comment by hoverlover** [comment]
Sorry about the mess.  I was learning a bit about the bot as I committed :)  I was going to rebase but I was afraid someone might have already pulled down the code.

**Comment by joshwand** [comment]
have updated the bot to be a gem. check it out and let me know how it works for you!

**Comment by cboyd-iseatz** [comment]
Cool!  I'll check it out soon.

**Comment by joshwand** [comment]
Can you give me access to update the campfire-bot gem on rubygems.org?

Thanks!

**Comment by hoverlover** [comment]
Done.

**Comment by joshwand** [comment]
:) fresh gem pushed!

**Pull request closed without merging**
